# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
